fabnumdef/e-chauffeur_api

- routes/campuses/cars.mjs
The first car on the list is also the last one used
> Select by default last car used by driver

- models/ride.mjs
- models/status.mjs
The first sms is now send on status "validated" instead of "accepted"
> Modify when the first SMS is send (status "validated")

- CHANGELOG.md
- middlewares/check-rights.mjs
- models/rules.mjs
- routes/pois.mjs
* Fix search location for campus rule
* Fix filters addition for POI CRUD
* Fix ctx param in check rights middleware
> Fix filters addition for POI CRUD

- CHANGELOG.md
- generate-vapid-key.js
- models/rating.mjs
- models/ride.mjs
- tests/routes/ratings.test.mjs
> Ensure that end date is after start date

- .gitlab-ci.yml
- .helm-chart/values.yaml
- package.json
> Migrate to helm3 & use self-signed certificates

- CHANGELOG.md
- fixtures/index.mjs
> Fix import-fixtures script

- CHANGELOG.md
- helpers/abstract-route.mjs
- routes/campuses.mjs
- routes/campuses/drivers.mjs
- routes/campuses/users.mjs
- routes/car-models.mjs
- routes/cars.mjs
- routes/categories.mjs
- routes/phone-models.mjs
- routes/phones.mjs
- routes/pois.mjs
- routes/ratings.mjs
- routes/users.mjs
> CSV middleware & lean update in abstract-route.mjs

- CHANGELOG.md
- models/user.mjs
> Deleted password from token

- CHANGELOG.md
- routes/rides.mjs
> Handled csv file formating without csv flatten

- CHANGELOG.md
- helpers/abstract-route.mjs
- routes/ratings.mjs
- tests/helpers/crud/create.mjs
- tests/routes/ratings.test.mjs
> Changed rating route status code to 204

- tests/routes/jwt.test.mjs
Checklist
^--- Unit test only, not relevant
> Ensure that token cannot be tested more than 3 times

- CHANGELOG.md
- routes/rides.mjs
> Throw err if ride departure === arrival

- CHANGELOG.md
- models/user.mjs
- tests/routes/users.test.mjs
> Limit email size

- CHANGELOG.md
- models/rights.mjs
- models/role.mjs
- routes/campuses/users.mjs
- routes/phones.mjs
- routes/pois.mjs
- tests/routes/cars.test.mjs
> Fix rights & scope management

- CHANGELOG.md
- models/user.mjs
- services/mail.mjs
- tests/routes/users.test.mjs
> Test email via regex

- CHANGELOG.md
- routes/users.mjs
> Fix proposal for rights when user is updated

- CHANGELOG.md
- models/rights.mjs
- routes/campuses/drivers-positions.mjs
- tests/routes/rides.test.mjs
- Added rights to drivers-positions.mjs
- Scoped CRUD rights to campus
Checklist
> Fixed some rights issues

- CHANGELOG.md
- models/campus.mjs
- tests/models/campus.mjs
- tests/routes/campuses.test.mjs
Checklist
Note : looks like mongoose required option in Schema does not behave as wishes with arrays. Thus validation was added to preValidate hook.
> Added required to coordinates in campus model

- CHANGELOG.md
- models/rights.mjs
> Fix drivers right to edit ride status

- CHANGELOG.md
- helpers/prefetch-ride.mjs
- models/campus.mjs
- models/car-model.mjs
- models/car.mjs
- models/category.mjs
- models/geo-tracking.mjs
- models/helpers/constants.mjs
- models/notification-device.mjs
- models/phone-model.mjs
- models/phone.mjs
- models/poi.mjs
- models/rating.mjs
- models/ride.mjs
- models/rights.mjs
- models/role.mjs
- models/time-slot.mjs
- models/user.mjs
- routes/campuses/drivers.mjs
- routes/campuses/stats.mjs
- routes/ratings.mjs
> Added ratings to campus stats route & created get route for rating

- models/campus.mjs
- models/rating.mjs
- models/ride.mjs
> Hotfix : ratings filtered by campus

- routes/users.mjs
HOTFIX : Added GPRD to sensitive data while self editing
> Fixed gprd self edit rights by adding it to sensitive data

- models/campus.mjs
> Hotfix Campus.countRides

- models/rating.mjs
- models/ride.mjs
> Hotfix generateCampusFilter static method on Ride and Rating

- models/ride.mjs
> Hotfix : avoid carModel and car validation for drafted rides

- models/ride.mjs
> Hotfixed : unwanted car validation on beforeSave and bug in capacity check

- models/ride.mjs
> Hotfixed car validation according to status in ride model

- models/ride.mjs
> Hotfixed validation when ride is not validated
